//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pozoriste.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public string ID_korisnika { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Korisnik Korisnik1 { get; set; }
    }
}
