//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pozoriste.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cijena_zone
    {
        public Cijena_zone()
        {

        }
        public Cijena_zone(int cijena, int idzone, int idsale, int idcjenovnika)
        {
            Cijena = cijena;
            Zona_ID_zone = idzone;
            Zona_Sala_ID_sale = idsale;
            Cjenovnik_id_cjenovnika = idcjenovnika;
        }
        public int Cijena { get; set; }
        public int Zona_ID_zone { get; set; }
        public int Zona_Sala_ID_sale { get; set; }
        public int Cjenovnik_id_cjenovnika { get; set; }
    
        public virtual Cjenovnik Cjenovnik { get; set; }
        public virtual Zona Zona { get; set; }
    }
}
