//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pozoriste.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Cjenovnik
    {
        public Cjenovnik()
        {
            this.Cijena_zone = new HashSet<Cijena_zone>();
        }

        public Cjenovnik(int id, DateTime poc, DateTime kraj, int id_izvedbe)
        {
            this.id_cjenovnika = id;
            this.pocetak_vazenja = poc;
            this.kraj_vazenja = kraj;
            this.Izvedba_ID_izvedbe = id_izvedbe;
        }
    
        public int id_cjenovnika { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Početak važenja")]
        public System.DateTime pocetak_vazenja { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Kraj važenja")]
        public System.DateTime kraj_vazenja { get; set; }
        public int Izvedba_ID_izvedbe { get; set; }
    
        public virtual ICollection<Cijena_zone> Cijena_zone { get; set; }
        public virtual Izvedba Izvedba { get; set; }
    }
}
