//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pozoriste.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Glumac
    {
        public Glumac()
        {
            this.Predstavas = new HashSet<Predstava>();
        }
    
        public int ID_glumca { get; set; }
        [Display(Name = "Ime")]
        public string Ime_glumca { get; set; }
        [Display(Name = "Prezime")]
        public string Prezime_glumca { get; set; }
    
        public virtual ICollection<Predstava> Predstavas { get; set; }
    }
}
