//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pozoriste.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Korisnik
    {
        [Display(Name = "Korisničko ime")]
        public string ID_korisnika { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        [Display(Name = "Šifra")]
        public string Sifra { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        public virtual Administrator Administrator1 { get; set; }
        public virtual Biletar Biletar { get; set; }
        public virtual Biletar Biletar1 { get; set; }
        public virtual Gledalac Gledalac { get; set; }
        public virtual Gledalac Gledalac1 { get; set; }
    }
}
