//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pozoriste.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class bazaPozoriste2Entities5 : DbContext
    {
        public bazaPozoriste2Entities5()
            : base("name=bazaPozoriste2Entities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Biletar> Biletars { get; set; }
        public virtual DbSet<Cjenovnik> Cjenovniks { get; set; }
        public virtual DbSet<Gledalac> Gledalacs { get; set; }
        public virtual DbSet<Glumac> Glumacs { get; set; }
        public virtual DbSet<Izvedba> Izvedbas { get; set; }
        public virtual DbSet<Korisnik> Korisniks { get; set; }
        public virtual DbSet<Organizator> Organizators { get; set; }
        public virtual DbSet<Predstava> Predstavas { get; set; }
        public virtual DbSet<Recenzija> Recenzijas { get; set; }
        public virtual DbSet<Red> Reds { get; set; }
        public virtual DbSet<Reditelj> Rediteljs { get; set; }
        public virtual DbSet<Repertoar> Repertoars { get; set; }
        public virtual DbSet<Rezervacija> Rezervacijas { get; set; }
        public virtual DbSet<Sala> Salas { get; set; }
        public virtual DbSet<Sjediste> Sjedistes { get; set; }
        public virtual DbSet<Zanr> Zanrs { get; set; }
        public virtual DbSet<Zona> Zonas { get; set; }
        public virtual DbSet<Cijena_zone> Cijena_zone { get; set; }
    
        public virtual int IntervaliIzvedbe(Nullable<int> id_predstave, Nullable<int> id_sale, Nullable<System.DateTime> datum, Nullable<System.TimeSpan> vrijeme)
        {
            var id_predstaveParameter = id_predstave.HasValue ?
                new ObjectParameter("Id_predstave", id_predstave) :
                new ObjectParameter("Id_predstave", typeof(int));
    
            var id_saleParameter = id_sale.HasValue ?
                new ObjectParameter("Id_sale", id_sale) :
                new ObjectParameter("Id_sale", typeof(int));
    
            var datumParameter = datum.HasValue ?
                new ObjectParameter("Datum", datum) :
                new ObjectParameter("Datum", typeof(System.DateTime));
    
            var vrijemeParameter = vrijeme.HasValue ?
                new ObjectParameter("Vrijeme", vrijeme) :
                new ObjectParameter("Vrijeme", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IntervaliIzvedbe", id_predstaveParameter, id_saleParameter, datumParameter, vrijemeParameter);
        }
    
        public virtual int PopuniZonu(Nullable<int> id_sale, Nullable<int> id_zone, Nullable<int> broj_redova, Nullable<int> sjedista_po_redu)
        {
            var id_saleParameter = id_sale.HasValue ?
                new ObjectParameter("id_sale", id_sale) :
                new ObjectParameter("id_sale", typeof(int));
    
            var id_zoneParameter = id_zone.HasValue ?
                new ObjectParameter("id_zone", id_zone) :
                new ObjectParameter("id_zone", typeof(int));
    
            var broj_redovaParameter = broj_redova.HasValue ?
                new ObjectParameter("broj_redova", broj_redova) :
                new ObjectParameter("broj_redova", typeof(int));
    
            var sjedista_po_reduParameter = sjedista_po_redu.HasValue ?
                new ObjectParameter("sjedista_po_redu", sjedista_po_redu) :
                new ObjectParameter("sjedista_po_redu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PopuniZonu", id_saleParameter, id_zoneParameter, broj_redovaParameter, sjedista_po_reduParameter);
        }
    }
}
