//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pozoriste.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;
    public partial class Predstava
    {
        public Predstava()
        {
            this.Izvedbas = new HashSet<Izvedba>();
            this.Recenzijas = new HashSet<Recenzija>();
            this.Glumacs = new HashSet<Glumac>();
            this.Rediteljs = new HashSet<Reditelj>();
        }
    
        public int ID_Predstave { get; set; }
        [Display(Name = "Naziv predstave")]
        public string Naziv_Predstave { get; set; }
        [Display(Name = "Dužina trajanja")]
        public int Duzina_trajanja { get; set; }
        [Display(Name = "Opis predstave")]
        public string Opis_predstave { get; set; }
        [Display(Name = "Organizator")]
        public int Organizator_ID_organizatora { get; set; }
        [Display(Name = "Žanr")]
        public int Zanr_ID_zanra { get; set; }
        public byte[] slika { get; set; }
    [NotMapped]
        public HttpPostedFileBase File { get; set; }
         [NotMapped]
    public String SlikaURL { get { return ID_Predstave.ToString() + ".jpg"; }  }
        public virtual ICollection<Izvedba> Izvedbas { get; set; }
        public virtual Organizator Organizator { get; set; }
        public virtual Zanr Zanr { get; set; }
        public virtual ICollection<Recenzija> Recenzijas { get; set; }
        public virtual ICollection<Glumac> Glumacs { get; set; }
        public virtual ICollection<Reditelj> Rediteljs { get; set; }
    }
}
