//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pozoriste.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Recenzija
    {
        public int ocjena { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime datum_ocjenjivanja { get; set; }
        public string komentar { get; set; }
        public string Gledalac_ID_korisnika { get; set; }
        public int Predstava_ID_Predstave { get; set; }
    
        public virtual Gledalac Gledalac { get; set; }
        public virtual Predstava Predstava { get; set; }
    }
}
