//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pozoriste.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Red
    {
        public Red()
        {
            this.Sjedistes = new HashSet<Sjediste>();
        }
    
        public int ID_reda { get; set; }
        public int Zona_ID_zone { get; set; }
        public int Zona_Sala_ID_sale { get; set; }
    
        public virtual Zona Zona { get; set; }
        public virtual ICollection<Sjediste> Sjedistes { get; set; }
    }
}
