//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pozoriste.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Rezervacija
    {
        [Display(Name = "Naziv rezervacije")]
        public string naziv_rezervacije { get; set; }
        [Display(Name = "Sjedište")]
        public int Sjediste_ID_sjedista { get; set; }
    
        public string Gledalac_ID_korisnika { get; set; }
        public int Izvedba_ID_izvedbe { get; set; }
        [Display(Name = "Red")]
        public int Sjediste_Red_ID_reda { get; set; }
        public int Sjediste_Red_Zona_ID_zone { get; set; }
        public int Sjediste_Red_Zona_Sala_ID_sale { get; set; }
    
        public virtual Gledalac Gledalac { get; set; }
        public virtual Izvedba Izvedba { get; set; }
        public virtual Sjediste Sjediste { get; set; }
    }
}
