//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pozoriste.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Sala
    {
        public Sala()
        {
            this.Izvedbas = new HashSet<Izvedba>();
            this.Zonas = new HashSet<Zona>();
        }
    
        public int ID_sale { get; set; }
        [Display(Name = "Naziv sale")]
        public string Naziv_Sale { get; set; }
    
        public virtual ICollection<Izvedba> Izvedbas { get; set; }
        public virtual ICollection<Zona> Zonas { get; set; }
    }
}
