//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pozoriste.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sjediste
    {
        public Sjediste()
        {
            this.Rezervacijas = new HashSet<Rezervacija>();
            this.Izvedbas = new HashSet<Izvedba>();
        }
    
        public int ID_sjedista { get; set; }
        public int Red_ID_reda { get; set; }
        public int Red_Zona_ID_zone { get; set; }
        public int Red_Zona_Sala_ID_sale { get; set; }
    
        public virtual Red Red { get; set; }
        public virtual ICollection<Rezervacija> Rezervacijas { get; set; }
        public virtual ICollection<Izvedba> Izvedbas { get; set; }
    }
}
