//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pozoriste.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Zona
    {
        public Zona()
        {
            this.Reds = new HashSet<Red>();
            this.Cijena_zone = new HashSet<Cijena_zone>();
        }
    
        public int ID_zone { get; set; }
        [Display(Name = "Naziv zone")]
        public string Naziv_zone { get; set; }
        public int Sala_ID_sale { get; set; }
    
        public virtual ICollection<Red> Reds { get; set; }
        public virtual Sala Sala { get; set; }
        public virtual ICollection<Cijena_zone> Cijena_zone { get; set; }
    }
}
